import Foundation

/// This class provides services to interact with Google Gemini AI for habit analysis.
/// It constructs prompts based on habit data, sends requests to the Gemini API, processes the responses and sends back insights.
/// 
/// # Properties
///  - `apiKey`: The API key used for authenticating requests to the Google Gemini API.
///  - `baseURL`: The base URL for the Gemini API endpoint.
/// # Methods
///  - `analyzeHabits(context:)`: Sends the habit analysis context to the Gemini API and returns the generated insights as a string.
///  - `buildAnalysisPrompt(context:)`: Constructs a detailed prompt for the Gemini API based on the provided habit analysis context.
///
/// - SeeAlso: `GeminiRequest`, `GeminiResponse`, `HabitAnalysisContext`
/// 
class GoogleAIService {
    private let apiKey = Secrets.geminiAPIKey
    
    private let baseURL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
    
    /// Errors that can occur during AI service interactions.
    /// 
    /// This enum conforms to `LocalizedError` to provide user-friendly error descriptions.
    /// It uses errorDescription to return appropriate messages for different error cases.
    /// 
    /// # Cases
    ///  - `invalidResponse`: Indicates that the response from the AI service was invalid.
    ///  - `apiError(String)`: Represents an error returned by the AI service, with an associated message.
    ///  - `noContent`: Indicates that the AI service did not generate any content in the response.
    /// 
    /// - SeeAlso: `GoogleAIService`
    enum AIServiceError: LocalizedError {
        case invalidResponse
        case apiError(String)
        case noContent
        
        var errorDescription: String? {
            switch self {
            case .invalidResponse:
                return "Invalid response from AI service"
            case .apiError(let message):
                return "AI Service Error: \(message)"
            case .noContent:
                return "No content generated by AI"
            }
        }
    }
    
    /// This function sends the habit analysis context to the Gemini API and returns the generated insights as a string.
    /// It constructs a prompt using buildAnalysisPrompt, uses the config, sends the request, and processes the response.
    ///
    /// - Parameters:
    ///  - context: The `HabitAnalysisContext` containing data about the habit to be analyzed.
    /// 
    /// - Returns: A string containing the insights generated by the AI.
    /// 
    /// - Throws: `AIServiceError` if there are issues with the request or response.
    ///
    func analyzeHabits(context: HabitAnalysisContext) async throws -> String {
        let prompt = buildAnalysisPrompt(context: context)
        
        let request = GeminiRequest(
            contents: [
                GeminiContent(
                    parts: [
                        GeminiPart(text: prompt)
                    ]
                )
            ],
            generationConfig: GeminiGenerationConfig(
                temperature: 0.7,
                maxOutputTokens: 1200
            )
        )
        
        let data = try JSONEncoder().encode(request)
        
        guard let url = URL(string: "\(baseURL)?key=\(apiKey)") else {
            throw AIServiceError.invalidResponse
        }
        
        var urlRequest = URLRequest(url: url)
        urlRequest.httpMethod = "POST"
        urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
        urlRequest.httpBody = data
        urlRequest.timeoutInterval = 30
        
        // Perform the request
        let (responseData, urlResponse) = try await URLSession.shared.data(for: urlRequest)
        
        // Check HTTP status code
        guard let httpResponse = urlResponse as? HTTPURLResponse else {
            throw AIServiceError.invalidResponse
        }
        
        // Debug logging
        print("HTTP Status Code: \(httpResponse.statusCode)")
        print("Response Data: \(String(data: responseData, encoding: .utf8) ?? "Unable to decode")")
        
        // Handle non-200 status codes
        if httpResponse.statusCode != 200 {
            // Try to parse error response
            if let errorResponse = try? JSONDecoder().decode(GeminiErrorResponse.self, from: responseData) {
                throw AIServiceError.apiError(errorResponse.error.message)
            } else {
                throw AIServiceError.apiError("HTTP \(httpResponse.statusCode): \(String(data: responseData, encoding: .utf8) ?? "Unknown error")")
            }
        }
        
        // Try to decode as JSON first to see the structure
        do {
            if let json = try JSONSerialization.jsonObject(with: responseData) as? [String: Any] {
                print("Raw JSON Response: \(json)")
                
                // Navigate through the response structure manually
                if let candidates = json["candidates"] as? [[String: Any]],
                   let firstCandidate = candidates.first,
                   let content = firstCandidate["content"] as? [String: Any] {
                    
                    // Try different possible response structures
                    if let parts = content["parts"] as? [[String: Any]],
                       let firstPart = parts.first,
                       let text = firstPart["text"] as? String {
                        return text
                    }
                    
                    // Alternative structure - text might be directly in content
                    if let text = content["text"] as? String {
                        return text
                    }
                    
                    // Another alternative - check if content itself is a string
                    if let contentText = content as? String {
                        return contentText
                    }
                }
                
                // Last resort - look for any "text" field in the response
                if let text = extractTextFromResponse(json: json) {
                    return text
                }
            }
            
            throw AIServiceError.noContent
            
        } catch {
            print("JSON parsing error: \(error)")
            
            // If JSON parsing fails, try the original approach
            do {
                let response = try JSONDecoder().decode(GeminiResponse.self, from: responseData)
                
                // Safe unwrapping of optional parts array
                guard let candidate = response.candidates.first,
                      let parts = candidate.content.parts,
                      let firstPart = parts.first,
                      !firstPart.text.isEmpty else {
                    throw AIServiceError.noContent
                }
                
                return firstPart.text
                
            } catch {
                print("Gemini response decoding error: \(error)")
                throw AIServiceError.invalidResponse
            }
        }
    }
    
    /// This function constructs a detailed prompt for the Gemini API based on the provided habit analysis context.
    /// The prompt includes habit details, context, and specific instructions for generating insights.
    /// 
    /// # The Habit details include:
    ///  - Name
    ///  - Category
    ///  - Frequency Goal
    ///  - Current Streak
    ///  - Overall Completion Rate
    ///  - Whether it was completed today
    ///  - Days since the habit was started
    ///  - Analysis Date
    /// 
    /// # The Prompt Context includes:
    ///  - Focus on a single habit
    ///  - User's desire for specific, personalized insights
    ///  - Consideration of the habit's frequency goal
    ///  - Evaluation of both short-term and long-term performance
    /// 
    /// # The Instructions specify:
    ///  - Provide exactly 3-4 structured insights in a specific format
    ///  - Insight types: critical, improvement, success, trend
    ///  - Focus areas for the insights
    ///  - Requirements for each insight to be specific, actionable, concise, and encouraging
    ///  - Importance of following the exact return format
    /// 
    /// - Parameters:
    ///  - context: The `HabitAnalysisContext` containing data about the habit to be analyzed.
    ///
    /// - Returns: A string containing the constructed prompt.
    /// - Throws: None
    /// - SeeAlso: `HabitAnalysisContext`
    /// 
    private func buildAnalysisPrompt(context: HabitAnalysisContext) -> String {
        let habit = context.habitData
        let completionPercentage = String(format: "%.1f", habit.completionRate * 100)
        
        let daysSinceStart = Calendar.current.dateComponents([.day], 
            from: Calendar.current.startOfDay(for: context.habitCreatedAt), 
            to: Calendar.current.startOfDay(for: context.analysisDate)).day ?? 1
        
        return """
        You are a habit analysis expert. Analyze the following single habit and provide actionable insights.
        
        HABIT ANALYSIS DATA:
        Habit Name: "\(habit.name)"
        Category: \(habit.category)
        Frequency Goal: \(habit.frequency)
        Current Streak: \(habit.currentStreak) days
        Overall Completion Rate: \(completionPercentage)%
        Completed Today: \(context.isCompletedToday ? "Yes" : "No")
        Days Since Started: \(daysSinceStart)
        Analysis Date: \(DateFormatter.localizedString(from: context.analysisDate, dateStyle: .medium, timeStyle: .none))
        
        INSTRUCTIONS:
        Provide exactly 3 structured insights in this EXACT format. Keep total response under 1200 tokens.
        
        [insight_type]
        [title]
        [description]
        ---
        
        Where insight_type must be one of: critical, improvement, success, trend
        
        Requirements:
        - Each insight must be under 60 words
        - Focus on actionable advice
        - Be specific to "\(habit.name)"
        - Keep descriptions concise and clear
        - Total response should be under 1200 tokens
        
        Example format:
        improvement
        Build Morning Momentum
        Start your day with this habit to create positive momentum. Set out materials the night before to reduce friction.
        ---
        
        IMPORTANT: 
        - Exactly 3 insights only
        - Each description under 60 words
        - Use "---" to separate insights
        - Keep total response brief and focused
        """
    }
    
    /// This function recursively searches through a JSON object to find and extract any "text" field.
    /// It handles nested dictionaries and arrays to locate the text.
    /// 
    /// - Parameters: 
    ///  - The JSON object to search through, which can be a dictionary, array, or string.
    /// 
    /// - Returns: An optional string containing the found text, or nil if not found.
    /// - Throws: None
    /// - SeeAlso: `GoogleAIService`
    private func extractTextFromResponse(json: Any) -> String? {
        if let string = json as? String {
            return string
        }
        
        if let dictionary = json as? [String: Any] {
            // Look for "text" key
            if let text = dictionary["text"] as? String {
                return text
            }
            
            // Recursively search in all values
            for value in dictionary.values {
                if let found = extractTextFromResponse(json: value) {
                    return found
                }
            }
        }
        
        if let array = json as? [Any] {
            for item in array {
                if let found = extractTextFromResponse(json: item) {
                    return found
                }
            }
        }
        
        return nil
    }
}